version: '3.8'

services:
    nginx:
        build:
            context: ./docker/local/nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - ./:/var/www
        depends_on:
            - php

    php:
        build:
            context: ./docker/local/php
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - mysql

    mysql:
        build:
            context: ./docker/local/mysql
            dockerfile: Dockerfile
        restart: always
        ports:
            - '${MYSQL_PORT}:3306'
        environment:
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_ROOT_PASSWORD: HFKLwei372rgusfkuw
            MYSQL_ROOT_HOST: '%'
        volumes:
            - mysql:/var/lib/mysql
            - ./docker/local/mysql/files/my-local.cnf:/etc/mysql/conf.d/my-local.cnf
volumes:
    mysql:

networks:
    default:
        driver: bridge
